import type { Metadata } from "next";
import { Anek_Bangla } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/Component/Navbar";
import Footer from "@/Component/Footer";
import Marquee from "@/Component/Marquee";

const anekBangla = Anek_Bangla({
  subsets: ["latin", "bengali"],
   weight: ['300', '400', '500', '600', '700'], 
  style: ['normal'],
  display: 'swap',
  variable: '--font-anek-bangla',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${anekBangla.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col max-w-7xl mx-auto">
        <Navbar />
        <Marquee />
         {children}
         <ToastContainer />
         <Footer />
      </body>
    </html>
  );
}
